---
services:
  backend:
    build: backend
    ports:
      - 8081:8081
    volumes:
      - ./backend/:/app/
    environment:
      - DEBUG=true
    entrypoint: ["uvicorn", "src.app:app", "--reload", "--reload-dir=src", "--port=8081", "--host=0.0.0.0"]

  frontend:
    build: frontend
    ports:
      - 8080:8080
    environment:
      - VITE_DOCKER=true
      - VITE_HOST=0.0.0.0
      - VITE_BACKEND_HOST=backend
    volumes:
      - ./frontend/:/app/
      - /app/node_modules

  pyroscope:
    image: "grafana/pyroscope:latest"
    ports:
      - 4040:4040
    command:
      - server
    volumes:
      # - ./configs/pyroscope.yaml:/etc/pyroscope/server.yaml
      - pyroscope_data:/var/lib/pyroscope

volumes:
  pyroscope_data:
